In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("free_meal_sites_philly.csv")

In [6]:
df.head()

,objectid,site_name,address,phone_number,category,zip_code,temporary_closure,category_type,site_key,status,...,hours_sat_start2,hours_sat_end2,hours_sat_exceptions,hours_sun_start1,hours_sun_end1,hours_sun_start2,hours_sun_end2,hours_sun_exceptions,email,seasonally_closed
0,104,Nativity Satellite Program,3255 Belgrade St,215-423-2772,PCA,19134.0,NaN,Senior Meal Site,1.0,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,118,King Older Adult Center,2100 W. Cecil B. Moore Ave.,215-685-2715,PPR_Senior,19121.0,NaN,Senior Meal Site,2.0,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,219,Bethel Worship Center,169 W. Wyoming Ave.,267-979-3718,SHARE FOOD PROGRAM,19120.0,NaN,Food Site,227.0,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,220,Hope Prison Ministries,735 W. Butler St.,610-633-1789,SHARE FOOD PROGRAM,19120.0,NaN,Food Site,210.0,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,221,Frontline Dads (410 N 34th St.),410 N 34th St,(484) 532-8772,SHARE FOOD PROGRAM,19104.0,NaN,Food Site,208.0,Permanently Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
Cleaned = df[["site_name","address", "category", "category_type", "status", "x", "y"]]

In [8]:
Cleaned.head()

,site_name,address,category,category_type,status,x,y
0,Nativity Satellite Program,3255 Belgrade St,PCA,Senior Meal Site,Active,-75.102783,39.986910
1,King Older Adult Center,2100 W. Cecil B. Moore Ave.,PPR_Senior,Senior Meal Site,Active,-75.169604,39.979985
2,Bethel Worship Center,169 W. Wyoming Ave.,SHARE FOOD PROGRAM,Food Site,Active,-75.127020,40.022040
3,Hope Prison Ministries,735 W. Butler St.,SHARE FOOD PROGRAM,Food Site,Active,-75.137593,40.026497
4,Frontline Dads (410 N 34th St.),410 N 34th St,SHARE FOOD PROGRAM,Food Site,Permanently Closed,-75.191289,39.961708

In [12]:
SuperCleaned = Cleaned.rename(columns={"site_name":"Site", "address": "Address", "category": "Category", "category_type": "Sub-category", "status": "Status", "x": "Longitude", "y": "Latitude"})

In [13]:
SuperCleaned.head()

,Site,Address,Category,Sub-category,Status,Longitude,Latitude
0,Nativity Satellite Program,3255 Belgrade St,PCA,Senior Meal Site,Active,-75.102783,39.986910
1,King Older Adult Center,2100 W. Cecil B. Moore Ave.,PPR_Senior,Senior Meal Site,Active,-75.169604,39.979985
2,Bethel Worship Center,169 W. Wyoming Ave.,SHARE FOOD PROGRAM,Food Site,Active,-75.127020,40.022040
3,Hope Prison Ministries,735 W. Butler St.,SHARE FOOD PROGRAM,Food Site,Active,-75.137593,40.026497
4,Frontline Dads (410 N 34th St.),410 N 34th St,SHARE FOOD PROGRAM,Food Site,Permanently Closed,-75.191289,39.961708

In [14]:
SuperCleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283 entries, 0 to 282
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Site          282 non-null    object
 1   Address       281 non-null    object
 2   Category      282 non-null    object
 3   Sub-category  281 non-null    object
 4   Status        281 non-null    object
 5   Longitude     175 non-null    float64
 6   Latitude      175 non-null    float64
dtypes: float64(2), object(5)
memory usage: 15.6+ KB

In [16]:
SuperCleaned.to_csv("FreeMealsClean.csv", index = False)