In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Philadelphia_Food_Access.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 19 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Census Tract                                          381 non-null    int64
 1   Population                                            381 non-null    int64
 2   Housing Units in Tract                                381 non-null    int64
 3   LI, LA - 1 mile radius                                381 non-null    int64
 4   LI, LA - 0.5 mile radius                              381 non-null    int64
 5   Low Income Tracts                                     381 non-null    int64
 6   Poverty Rate (%)                                      381 non-null    float64
 7   Median Family Income                                  369 non-null    float64
 8   LA - 1 mile radius                                    381 non-null    int64
 9   LA - 0.5 mile radius                                  381 non-null    int64
 10  LA,LI - 0.5 mile radius                               242 non-null    float64
 11  LA - Kids population, 0.5 mile radius                 242 non-null    float64
 12  LA - Senior population, 0.5 mile radius               242 non-null    float64
 13  LA - Kids population, 1 mile radius                   34 non-null     float64
 14  LA - Senior population, 1 mile radius                 34 non-null     float64
 15  LA - Housing Units w/ Snap Benefits, 0.5 mile radius  242 non-null    float64
 16  LA - Housing Units w/ Snap Benefits, 1 mile radius    34 non-null     float64
 17  Total Count of Housing w/ Snap Benefits               381 non-null    int64
 18  Snap Percentage                                       381 non-null    float64
dtypes: float64(10), int64(9)
memory usage: 56.7 KB

In [4]:
df['Snap Percentage'] = df['Snap Percentage'].astype(int)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 19 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Census Tract                                          381 non-null    int64
 1   Population                                            381 non-null    int64
 2   Housing Units in Tract                                381 non-null    int64
 3   LI, LA - 1 mile radius                                381 non-null    int64
 4   LI, LA - 0.5 mile radius                              381 non-null    int64
 5   Low Income Tracts                                     381 non-null    int64
 6   Poverty Rate (%)                                      381 non-null    float64
 7   Median Family Income                                  369 non-null    float64
 8   LA - 1 mile radius                                    381 non-null    int64
 9   LA - 0.5 mile radius                                  381 non-null    int64
 10  LA,LI - 0.5 mile radius                               242 non-null    float64
 11  LA - Kids population, 0.5 mile radius                 242 non-null    float64
 12  LA - Senior population, 0.5 mile radius               242 non-null    float64
 13  LA - Kids population, 1 mile radius                   34 non-null     float64
 14  LA - Senior population, 1 mile radius                 34 non-null     float64
 15  LA - Housing Units w/ Snap Benefits, 0.5 mile radius  242 non-null    float64
 16  LA - Housing Units w/ Snap Benefits, 1 mile radius    34 non-null     float64
 17  Total Count of Housing w/ Snap Benefits               381 non-null    int64
 18  Snap Percentage                                       381 non-null    int32
dtypes: float64(9), int32(1), int64(9)
memory usage: 55.2 KB

In [7]:
df.to_csv("Philadelphia_Food_Access2.csv", index = False)

In [8]:
SuperCleaned.head()

,Census Tract,Population,Housing Units in Tract,"LI, LA - 1 mile radius","LI, LA - 0.5 mile radius",Low Income Tracts,Poverty Rate (%),Median Family Income,LA - 1 mile radius,LA - 0.5 mile radius,"LA,LI - 0.5 mile radius","LA - Kids population, 0.5 mile radius","LA - Senior population, 0.5 mile radius","LA - Kids population, 1 mile radius","LA - Senior population, 1 mile radius","LA - Housing Units w/ Snap Benefits, 0.5 mile radius","LA - Housing Units w/ Snap Benefits, 1 mile radius",Total Count of Housing w/ Snap Benefits
0,42101000100,3478,2301,0,0,0,6.937110,124729.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12
1,42101000200,2937,1145,0,0,1,29.253366,47806.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95
2,42101000300,3169,1855,0,0,0,9.255220,143482.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32
3,42101000401,2125,1584,0,0,0,17.697394,129531.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202
4,42101000402,3142,2273,0,0,0,4.690722,125917.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78

In [9]:
SuperCleaned['Poverty Rate (%)'] = SuperCleaned['Poverty Rate (%)'].astype(float)

In [10]:
SuperCleaned.style.format({'Poverty Rate (%)': '{:,.2f}'.format, 'Median Family Income': '{:,.2f}'.format, 'LA,LI - 0.5 mile radius': '{:,.2f}'.format, 'LA - Kids population, 0.5 mile radius': '{:,.2f}'.format, 'LA - Senior population, 0.5 mile radius': '{:,.2f}'.format, 'LA - Kids population, 1 mile radius': '{:,.2f}'.format, 'LA - Senior population, 1 mile radius': '{:,.2f}'.format,'LA - Housing Units w/ Snap Benefits, 0.5 mile radius': '{:,.2f}'.format, 'LA - Housing Units w/ Snap Benefits, 1 mile radius': '{:,.2f}'.format})

In [11]:
SuperCleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 18 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Census Tract                                          381 non-null    int64
 1   Population                                            381 non-null    int64
 2   Housing Units in Tract                                381 non-null    int64
 3   LI, LA - 1 mile radius                                381 non-null    int64
 4   LI, LA - 0.5 mile radius                              381 non-null    int64
 5   Low Income Tracts                                     381 non-null    int64
 6   Poverty Rate (%)                                      381 non-null    float64
 7   Median Family Income                                  369 non-null    float64
 8   LA - 1 mile radius                                    381 non-null    int64
 9   LA - 0.5 mile radius                                  381 non-null    int64
 10  LA,LI - 0.5 mile radius                               242 non-null    float64
 11  LA - Kids population, 0.5 mile radius                 242 non-null    float64
 12  LA - Senior population, 0.5 mile radius               242 non-null    float64
 13  LA - Kids population, 1 mile radius                   34 non-null     float64
 14  LA - Senior population, 1 mile radius                 34 non-null     float64
 15  LA - Housing Units w/ Snap Benefits, 0.5 mile radius  242 non-null    float64
 16  LA - Housing Units w/ Snap Benefits, 1 mile radius    34 non-null     float64
 17  Total Count of Housing w/ Snap Benefits               381 non-null    int64
dtypes: float64(9), int64(9)
memory usage: 53.7 KB

In [12]:
SuperCleaned.to_csv("Philadelphia Food Access.csv", index = False)