In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("Farmers_Markets_Philly.csv")

In [6]:
df.head()

,X,Y,objectid,globalid,editdate,name,operator,address,zip,transit_parking,...,payment_philly_food_bucks,transit_trolley,season_year_round,season_opening_month,season_opening_day,season_closing_month,season_closing_day,payment_cash,payment_other_low_cost,payment_low_cost
0,-75.220694,40.025777,1,02394865-c6e5-48d7-8162-0c7929b21bdf,2025/01/23 05:02:36+00,Pretzel Park Farmers' Market,Friends of Pretzel Park,4300 Silverwood Street,19127,"FOST,POFFS",...,No,NaN,Yes,NaN,NaN,NaN,NaN,Yes,NaN,No
1,-75.171580,39.950286,2,56f87743-3148-4acf-b76f-93737cde82f2,2025/01/23 05:02:36+00,Rittenhouse Farmers' Market,Farm to City,1800 Walnut Street,19103,"FOST,POFFS",...,No,"10, 13, 34, 11, 36",Yes,NaN,NaN,NaN,NaN,Yes,NaN,No
2,-75.215926,39.932614,3,715fa94c-8798-4159-8121-f0de852747da,2025/01/23 05:02:36+00,Sankofa Farmstand,Sasha Hubert and Chris Newsome,54th and Lindbergh Blvd,19144,FOST,...,Yes,NaN,No,June,13.0,November,21.0,Yes,Community members may volunteer at our 2nd and...,Yes
3,-75.156717,39.950026,4,2f4f4aff-b33b-43d7-9f9f-0f8c73af04f6,2025/01/23 05:02:36+00,Jefferson Farmers' Market,Farm to City,925 Chestnut Street,19107,"MOST,PGP,POFFS",...,No,NaN,No,May,NaN,November,21.0,Yes,NaN,No
4,-75.162307,39.931053,5,f656f958-3eba-4719-a89e-2ddd10cc173b,2025/01/23 05:02:36+00,East Passyunk Farmers' Market,Farm to City,1430 E. Passyunk Avenue,19147,"FOST,MOST,FOFFS",...,No,NaN,No,June,12.0,November,NaN,Yes,NaN,No

In [8]:
Cleaned = df[["objectid","name", "address", "zip", "payment_snap", "X", "Y"]]

In [9]:
Cleaned.head()

,objectid,name,address,zip,payment_snap,X,Y
0,1,Pretzel Park Farmers' Market,4300 Silverwood Street,19127,No,-75.220694,40.025777
1,2,Rittenhouse Farmers' Market,1800 Walnut Street,19103,No,-75.171580,39.950286
2,3,Sankofa Farmstand,54th and Lindbergh Blvd,19144,Yes,-75.215926,39.932614
3,4,Jefferson Farmers' Market,925 Chestnut Street,19107,No,-75.156717,39.950026
4,5,East Passyunk Farmers' Market,1430 E. Passyunk Avenue,19147,No,-75.162307,39.931053

In [11]:
SuperCleaned = Cleaned.rename(columns={"objectid":"Count", "name": "Name", "address": "Address", "zip": "Zipcode", "payment_snap": "Accepts SNAP", "X": "Longitude", "Y": "Latitude"})

In [12]:
SuperCleaned.head()

,Count,Name,Address,Zipcode,Accepts SNAP,Longitude,Latitude
0,1,Pretzel Park Farmers' Market,4300 Silverwood Street,19127,No,-75.220694,40.025777
1,2,Rittenhouse Farmers' Market,1800 Walnut Street,19103,No,-75.171580,39.950286
2,3,Sankofa Farmstand,54th and Lindbergh Blvd,19144,Yes,-75.215926,39.932614
3,4,Jefferson Farmers' Market,925 Chestnut Street,19107,No,-75.156717,39.950026
4,5,East Passyunk Farmers' Market,1430 E. Passyunk Avenue,19147,No,-75.162307,39.931053

In [13]:
SuperCleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Count         22 non-null     int64
 1   Name          22 non-null     object
 2   Address       22 non-null     object
 3   Zipcode       22 non-null     int64
 4   Accepts SNAP  21 non-null     object
 5   Longitude     22 non-null     float64
 6   Latitude      22 non-null     float64
dtypes: float64(2), int64(2), object(3)
memory usage: 1.3+ KB

In [14]:
SuperCleaned.to_csv("FarmersMarketClean.csv", index = False)